# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 200
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - simple_gripper_right_driver_joint
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
simple_gripper:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  joint_position_controller:
     type: position_controllers/GripperActionController
     joint: simple_gripper_right_driver_joint

  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - simple_gripper_right_driver_joint

  controller_list:
    - name: "joint_position_controller"
      action_ns: gripper_cmd
      type: GripperCommand
      default: true
      joints:
        - simple_gripper_right_driver_joint
